name: Compilability check
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        abi: [ "armeabi-v7a", "arm64-v8a"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Setup the environment
        run: |
          sudo pip3 install meson==0.57.1
          sudo apt-get install nasm ninja-build

      - name: Executing the script
        run: |
          export ANDROID_SDK_HOME=$ANDROID_HOME
          ./ffmpeg-android-maker.sh -all-free -all-gpl -android=19 -abis=${{ matrix.abi }}

      - uses: actions/upload-artifact@v2
        with:
          name: artifact-ffmpeg
          path: output/
